export const videoData = [
  {
    video: require('./storage/videos/v1.mp4'),
    postProfile: require('./storage/images/kv.png'),
    title: 'khanhvyccf',
    description: 'Driving on the road...',
    likes: '245k',
    isLike: false,
  },
  {
    video: require('./storage/videos/v2.mp4'),
    postProfile: require('./storage/images/post3.png'),
    title: 'anthony.haidang',
    description: 'Feel the beauty of nature',
    likes: '245k',
    isLike: false,
  },
  {
    video: require('./storage/videos/v3.mp4'),
    postProfile: require('./storage/images/st.png'),
    title: 'sontungmtp',
    description: 'Wanna drink some coffee?',
    likes: '245k',
    isLike: false,
  },
  {
    video: require('./storage/videos/v4.mp4'),
    postProfile: require('./storage/images/tt.png'),
    title: 'mia.soya',
    description: 'Looking the city from the apartment',
    likes: '245k',
    isLike: false,
  },
  {
    video: require('./storage/videos/v5.mp4'),
    postProfile: require('./storage/images/mn.png'),
    title: 'mono.hng',
    description: 'The sunset...',
    likes: '245k',
    isLike: false,
  },
];

export const friendsProfileData = [
  {
    name: 'sontungmtp',
    accountName: 'Sơn Tùng M-TP',
    profileImage: require('./storage/images/st.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mono.hng',
    accountName: 'Mono',
    profileImage: require('./storage/images/mn.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mia.soya',
    accountName: 'Nguyen Lam Thao Tam',
    profileImage: require('./storage/images/tt.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'khanhvyccf',
    accountName: 'Khánh Vy',
    profileImage: require('./storage/images/kv.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'sontungmtp',
    accountName: 'Sơn Tùng M-TP',
    profileImage: require('./storage/images/st.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mono.hng',
    accountName: 'Mono',
    profileImage: require('./storage/images/mn.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mia.soya',
    accountName: 'Nguyen Lam Thao Tam',
    profileImage: require('./storage/images/tt.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'khanhvyccf',
    accountName: 'Khánh Vy',
    profileImage: require('./storage/images/kv.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  ,
  {
    name: 'sontungmtp',
    accountName: 'Sơn Tùng M-TP',
    profileImage: require('./storage/images/st.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mono.hng',
    accountName: 'Mono',
    profileImage: require('./storage/images/mn.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mia.soya',
    accountName: 'Nguyen Lam Thao Tam',
    profileImage: require('./storage/images/tt.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'khanhvyccf',
    accountName: 'Khánh Vy',
    profileImage: require('./storage/images/kv.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
];
