export const videoData = [
  {
    video:
      'https://firebasestorage.googleapis.com/v0/b/instagram-381915.appspot.com/o/instagram%2F05052023064657reels.mp4?alt=media&token=acac70d0-02ff-4757-b328-175781796785',
    postProfile: require('./storage/images/kv.png'),
    title: 'khanhvyccf',
    description: 'Driving on the road...',
    likes: '245K',
    comments: '3.5M',
    shares: '2.1K',
    isLike: false,
  },
  {
    video:
      'https://firebasestorage.googleapis.com/v0/b/instagram-381915.appspot.com/o/instagram%2F51202341240PM2.mp4?alt=media&token=a649dc23-5b94-4b3a-a038-d922c53439b6',
    postProfile: require('./storage/images/post3.png'),
    title: 'anthony.haidang',
    description: 'Feel the beauty of nature',
    likes: '245K',
    comments: '3.5M',
    shares: '2.1K',
    isLike: false,
  },
  {
    video:
      'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    postProfile: require('./storage/images/st.png'),
    title: 'sontungmtp',
    description: 'Wanna drink some coffee?',
    likes: '245K',
    comments: '3.5M',
    shares: '2.1K',
    isLike: false,
  },
  {
    video:
      'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    postProfile: require('./storage/images/tt.png'),
    title: 'mia.soya',
    description: 'Looking the city from the apartment',
    likes: '245K',
    comments: '3.5M',
    shares: '2.1K',
    isLike: false,
  },
  {
    video:
      'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    postProfile: require('./storage/images/mn.png'),
    title: 'mono.hng',
    description: 'The sunset...',
    likes: '245K',
    comments: '3.5M',
    shares: '2.1K',
    isLike: false,
  },
];

export const friendsProfileData = [
  {
    name: 'sontungmtp',
    accountName: 'Sơn Tùng M-TP',
    profileImage: require('./storage/images/st.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mono.hng',
    accountName: 'Mono',
    profileImage: require('./storage/images/mn.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mia.soya',
    accountName: 'Nguyen Lam Thao Tam',
    profileImage: require('./storage/images/tt.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'khanhvyccf',
    accountName: 'Khánh Vy',
    profileImage: require('./storage/images/kv.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'sontungmtp',
    accountName: 'Sơn Tùng M-TP',
    profileImage: require('./storage/images/st.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mono.hng',
    accountName: 'Mono',
    profileImage: require('./storage/images/mn.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mia.soya',
    accountName: 'Nguyen Lam Thao Tam',
    profileImage: require('./storage/images/tt.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'khanhvyccf',
    accountName: 'Khánh Vy',
    profileImage: require('./storage/images/kv.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  ,
  {
    name: 'sontungmtp',
    accountName: 'Sơn Tùng M-TP',
    profileImage: require('./storage/images/st.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mono.hng',
    accountName: 'Mono',
    profileImage: require('./storage/images/mn.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'mia.soya',
    accountName: 'Nguyen Lam Thao Tam',
    profileImage: require('./storage/images/tt.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'khanhvyccf',
    accountName: 'Khánh Vy',
    profileImage: require('./storage/images/kv.png'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
];
